name: Discord Test

on:
  workflow_dispatch: # lets you trigger manually from Actions tab

jobs:
  ping-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Test Message
        uses: Ilshidur/action-discord@master
        env:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "✅ Hello from GitHub Actions!"
