name: Enforce Rebase

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  check-rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Check merge base
        id: rebase_check
        run: |
          git fetch origin main
          MERGE_BASE=$(git merge-base HEAD origin/main)
          LATEST_MAIN=$(git rev-parse origin/main)
          echo "MERGE_BASE: $MERGE_BASE"
          echo "LATEST_MAIN: $LATEST_MAIN"

          # Ensure PR branch is directly on top of main
          if [ "$MERGE_BASE" != "$LATEST_MAIN" ]; then
            echo "Branch is not rebased on latest main. Run git fetch, git rebase origin/main and then resolve any/all merge conflicts with the Merge Editor. Continue the rebase with git rebase --continue until your rebase has completed successfully. Finish with git push --force to rebase."
            echo "status=failure" >> $GITHUB_OUTPUT
            exit 1
          else
            echo "status=success" >> $GITHUB_OUTPUT
          fi

      - name: Set PR status to success
        if: steps.rebase_check.outputs.status == 'success'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: process.env.GITHUB_SHA,
              state: 'success',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions`,
              description: 'Branch is rebased on latest main.',
              context: 'Manual Check'
            });

      - name: Set PR status to failure
        if: steps.rebase_check.outputs.status == 'failure'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: process.env.GITHUB_SHA,
              state: 'failure',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions`,
              description: 'Branch is not rebased on latest main.',
              context: 'Manual Check'
            });
