name: Enforce Rebase

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check-rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Check merge base
        run: |
          git fetch origin main
          MERGE_BASE=$(git merge-base HEAD origin/main)
          LATEST_MAIN=$(git rev-parse origin/main)
          echo "MERGE_BASE: $MERGE_BASE"
          echo "LATEST_MAIN: $LATEST_MAIN"

          # Ensure PR branch is directly on top of main
          if [ "$MERGE_BASE" != "$LATEST_MAIN" ]; then
            echo "Branch is not rebased on latest main. Run git fetch, git rebase origin/main and then resolve all merge conflicts with the Merge Editor. Continue the rebase with git rebase --continue until your rebase has completed successfully. Finish with git push --force to rebase."
            exit 1
          fi
